[package]
name = "cpu_benchmark"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
default-run = "benchmark"

[dependencies]
clap.workspace = true

[[bin]]
name = "benchmark"
path = "src/main.rs"
